<a href="https://colab.research.google.com/github/codewithsamiksha/Games/blob/main/Session_13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Q1
import numpy as np
#deatils of 1D Array
arr_1D= np.array([10, 20, 30, 40, 50])
print("1D Array = ", arr_1D)
print("Shape of 1D Array =", arr_1D.shape)
print("Datatype of 1D Array = ",arr_1D.dtype)
print()

#deatils of 2D Array
arr_2D = np.array([[10, 20, 30],[40, 50, 60]])
print("2D Array = ", arr_2D)
print("Shape of 2D Array = ",arr_2D.shape)
print("Datatype of 2D Array = ",arr_2D.dtype)

1D Array =  [10 20 30 40 50]
Shape of 1D Array = (5,)
Datatype of 1D Array =  int64

2D Array =  [[10 20 30]
 [40 50 60]]
Shape of 2D Array =  (2, 3)
Datatype of 2D Array =  int64


In [2]:
#Q2
# A 1D array of 8 zeros.
arr_1D = np.zeros(8)
print("1D Array of 8 Zeros = ",arr_1D)
print()

#A 2D array of shape 4, 4) filled with ones.
ones_2D = np.ones((4,4))
print("2D Array of ones = ", ones_2D)
print()

# A 3 3 matrix of zeros.
zeros_2D = np.zeros((3,3))
print("Matrix of Zeros = ", zeros_2D)

1D Array of 8 Zeros =  [0. 0. 0. 0. 0. 0. 0. 0.]

2D Array of ones =  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Matrix of Zeros =  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
#Q3
#Numbers from 0 to 20 (step 1)
arr = np.arange(0, 20)
print("Numbers from 0 to 20 = ", arr)

#Even numbers from 10 to 50.
even_arr = np.arange(10 , 50 , 2)
print("Even numbers from 10 to 50 = ", even_arr)

# Numbers from 5 to 100 with step of 5.
arr2 = np.arange(5, 100, 5)
print("Numbers from 5 to 100 with step of 5 = ",arr2)

Numbers from 0 to 20 =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Even numbers from 10 to 50 =  [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
Numbers from 5 to 100 with step of 5 =  [ 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [4]:
#Q4
#10 equally spaced numbers between 0 and 5.
num1 = np.linspace(0,5,10)
print("Number = ",num1)
print("Length Of Num1 = ", len(num1))
print()

#15 equally spaced numbers between 10 and 10.
num2 = np.linspace(-10, 10, 15)
print("Numbers = ", num2)
print("Length Of Num2 = ", len(num2))


Number =  [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
Length Of Num1 =  10

Numbers =  [-10.          -8.57142857  -7.14285714  -5.71428571  -4.28571429
  -2.85714286  -1.42857143   0.           1.42857143   2.85714286
   4.28571429   5.71428571   7.14285714   8.57142857  10.        ]
Length Of Num2 =  15


In [5]:
#Q5
#A 1D array of 10 random numbers between 0 and 1 using np.random.rand().
import random
arr1 = np.random.rand(10)
print("Array of 10 Random Number = ", arr1)
print()

# 3 3 matrix of random numbers
arr2 = np.random.randn(3, 3)
print("3 By 3 matrix = ",arr2)
print()

#A 2D array 4 5 of interger
arr3 = np.random.randint(10,50, (4,5))
print("A 2D array 4 by 5 of interger = ", arr3)


Array of 10 Random Number =  [0.03973187 0.88346333 0.97739446 0.06572367 0.65287468 0.74104428
 0.5503525  0.69059634 0.08983759 0.9407026 ]

3 By 3 matrix =  [[-0.5216367  -1.10753654  0.68329814]
 [-2.61351567  0.75183555 -2.09814232]
 [-1.10006372 -1.21044625  0.73825756]]

A 2D array 4 by 5 of interger =  [[37 48 12 10 19]
 [40 38 31 32 25]
 [13 11 30 49 30]
 [31 35 10 26 32]]


In [6]:
#Q6
v1 = np.array([2, 4, 6, 8])
v2 = np.array([1, 3, 5, 7])

#Addition
print("Addition of v1 and v2 = ",v1 + v2)
print()

#Subtraction
print("Subtraction of v1 and v2 = ", v1-v2)
print()

#Element-wise multiplication
print("Element-wise multiplication = ", v1 * v2)
print()

#Dot product
print("Dot product of v1 and v2 = ",np.dot(v1,v2))
print()


Addition of v1 and v2 =  [ 3  7 11 15]

Subtraction of v1 and v2 =  [1 1 1 1]

Element-wise multiplication =  [ 2 12 30 56]

Dot product of v1 and v2 =  100



In [7]:
#Q7
A = np.array ([[1,2,3],[4,5,6],[7,8,9]])
B = np.array ([[9,8,7],[6,5,4],[3,2,1]])

print("A = ", A)
print("B = ", B)
print()

#Matrix addition
print("Addition = ", A + B)
print()

#Matrix multiplication (@ or np.dot())
print("Matrix multiplication = ", np.dot(A, B))
print()

#Element-wise multiplication (*)
print("Element-wise multiplication (*) = ",A * B )
print()

A =  [[1 2 3]
 [4 5 6]
 [7 8 9]]
B =  [[9 8 7]
 [6 5 4]
 [3 2 1]]

Addition =  [[10 10 10]
 [10 10 10]
 [10 10 10]]

Matrix multiplication =  [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Element-wise multiplication (*) =  [[ 9 16 21]
 [24 25 24]
 [21 16  9]]



In [8]:
#Q8
matrix = np.random.randint(1,100,(4,4))
print(matrix )
print()

#Shape
print("Shape = ", matrix.shape)
print()

#Dimension (ndim)
print("Dimension = ", matrix.ndim)
print()

#Total number of elements (size)
print("Total Number of Element = ",matrix.size)
print()

#Data type
print("Datatype = ", matrix.dtype)
print()

#Minimum and maximum values
print("Minimum = ", np.min(matrix))
print("Maxzimum = ", np.max(matrix))


[[93  3 45 16]
 [35  8 14 78]
 [34 80 16 49]
 [81 22 69 11]]

Shape =  (4, 4)

Dimension =  2

Total Number of Element =  16

Datatype =  int64

Minimum =  3
Maxzimum =  93


In [9]:
#Q9
#1D arr of 20 random number between 1 to 50
v1 = np.random.randint(1, 50, 20)
print(v1)
print()

#Reshape it into a 4 5 matrix.
print("Reshape = ", v1.reshape(4,5))
print()

#Print the sum, mean, and standard deviation of the matrix.
print("Sum = ", np.sum(v1))
print("Maen = ",np.mean(v1))
print("Deviation of matrix = ",np.std(v1))


#Find the maximum value in each row.
print("Maximum Value = ", np.max(matrix, axis=1))

[36 15 30 41 28 11 46 16 10  3 26 25  8 18  7 49 31 40 23 43]

Reshape =  [[36 15 30 41 28]
 [11 46 16 10  3]
 [26 25  8 18  7]
 [49 31 40 23 43]]

Sum =  506
Maen =  25.3
Deviation of matrix =  13.7189649755366
Maximum Value =  [93 78 80 81]


In [10]:
#Q10
# Ask the user how many numbers to generate
try:
  n = int(input("How many numbers do you want to generate? "))

  if (n <= 0):
    print("Invalid Input.. please enter positive number")

  else:
    # Generate random numbers between 10 and 100
    arr = np.random.randint(10, 101, n)
    print("Array = ",arr)
    print()

    #Mean, Median, Standard Deviation
    print("Mean = ", np.mean(arr))
    print("Median = ",np.median(arr))
    print("Standard Deviation = ",np.std(arr))

    #Minimum and Maximum
    print("Minimum = ", np.min(arr))
    print("Maximun = ", np.max(arr))

    #Reshapes into a 2D array
    matrix = arr.reshape(n//2,2)
    if (n % 2 == 0):
      print("2D Array = ",matrix)

      # prints row-wise sum
      print("Row wise sum = ")
      print(np.sum(matrix, axis=1))
    else:
      print("Reshape Cannot posiable")
except ValueError:
  print("Error: Invalid Input..!! Please enter integer value")


How many numbers do you want to generate? 8
Array =  [43 57 20 52 19 86 39 96]

Mean =  51.5
Median =  47.5
Standard Deviation =  26.16772821625905
Minimum =  19
Maximun =  96
2D Array =  [[43 57]
 [20 52]
 [19 86]
 [39 96]]
Row wise sum = 
[100  72 105 135]
